# Generated by Django 4.0.6 on 2022-07-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_fir_firs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FIRs',
            new_name='FIR',
        ),
    ]
