# Generated by Django 4.0.6 on 2022-07-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_addcomplaint_complaint_delete_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
