# Generated by Django 4.0.6 on 2022-07-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_delete_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFir',
        ),
    ]
