# Generated by Django 4.0.6 on 2022-07-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_delete_addfir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
